backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections: # A list of collections the CMS should be able to edit
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "global-settings"
        label: "Global Settings"
        file: "data/settings/global.yml"
        description: "Global Site Settings"
        fields:
          - {label: "Global title", name: siteTitle, widget: string}
          - {label: "Site Url", name: siteUrl, widget: url}
          - label: "Colors"
            name: colors
            widget: object
            fields:
              - {label: "Primary Color", name: colorPrimary, widget: color}
      - name: "product-settings"
        label: "Product Settings"
        file: "data/settings/product.yml"
        description: "Global Product Settings"
        fields:
          - {label: "Show Related Products?", name: relatedProducts, widget: "boolean", default: true}
          - {label: "Show Breadcrumbs on Product Page?", name: breadcrumbs, widget: "boolean", default: true}
          - {label: "Primary Color", name: colorPrimary, widget: string}
