backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections: # A list of collections the CMS should be able to edit
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "global-settings"
        label: "Global Settings"
        file: "data/settings/global.json"
        description: "Global Site Settings"
        fields:
          - {label: "Global title", name: siteTitle, widget: string}
          - {label: "Site Url", name: siteUrl, widget: string}
          - {label: "Favicon", name: favicon, widget: image}
      - name: "theme-settings"
        label: "Theme Settings"
        file: "data/settings/theme.json"
        description: "Theme Settings"
        fields:
          - label: "Colors - General"
            name: colors
            widget: object
            fields:
              - {label: "Primary Color", name: colorPrimary, widget: color}
          - label: "Typography - Headings"
            name: headingTypography
            widget: object
            fields:
              - {label: "Font Family", name: fontFamily, widget: string}
              - {label: "Display headings in uppercase", name: uppercase, widget: boolean}
          - label: "Typography - Body Text"
            name: bodyTypography
            widget: object
            fields:
              - {label: "Font Family", name: fontFamily, widget: string}
              - {label: "Base Font Size", name: fontSize, widget: string}
      - name: "product-settings"
        label: "Product Settings"
        file: "data/settings/product.json"
        description: "Global Product Settings"
        fields:
          - {label: "Show Related Products?", name: relatedProducts, widget: "boolean", default: true}
          - {label: "Show Breadcrumbs on Product Page?", name: breadcrumbs, widget: "boolean", default: true}
          - {label: "Primary Color", name: colorPrimary, widget: string}
